### ISSUE TITLE
API change braking the action

### ISSUE THREAD

**Issue by TomerFi** [pozil/auto-assign-issue#6]
The action has stopped working, throwing the following (**but not failing the workflow**):

```text
(node:2419) UnhandledPromiseRejectionWarning: TypeError: github.GitHub is not a constructor
    at run (/home/runner/work/_actions/pozil/auto-assign-issue/v1.0.2/src/index.js:7:21)
    at Object.<anonymous> (/home/runner/work/_actions/pozil/auto-assign-issue/v1.0.2/src/index.js:39:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
(node:2419) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2419) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This should be easy to fix, I will open a PR soon.

**Comment by pozil** [comment]
Hi @TomerFi, thanks a lot for opening this issue and providing the related PRs.
I missed that breaking change when I merged a Dependabot PR :(
I'll merge your PRs right away, thx again for contributing.

**Comment by pozil** [comment]
Fixed in v1.0.3

**Comment by TomerFi** [comment]
@pozil Thank you for sharing this action and accepting my PR.
I've just tested v1.0.3 and it works as expected.
:-)
