### ISSUE TITLE
Allow Github App access token for teams

### ISSUE THREAD

**Issue by figadore** [pozil/auto-assign-issue#91]
> Important Requirement: if using the teams input parameter, you need to use a personal access token with read:org scope (the default GITHUB_TOKEN is not enough).

We can't use personal access tokens here, so I'm trying to get this to work with a Github App's access token. I've given the app permission to read the org's members and teams
![image](https://user-images.githubusercontent.com/3253971/213026052-d0efc48c-9f3a-4b70-8574-f8ff0ac570fb.png)

I'm using [an action](https://github.com/vivantehealth/gh-app-access-token-action/blob/main/index.js) that returns an access token for the app, but it doesn't seem to work in the `repo-token` field

The error I'm getting is 

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Failed to retrieve team members
    at /home/runner/work/_actions/pozil/auto-assign-issue/v1/src/utils.js:41:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getTeamMembers (/home/runner/work/_actions/pozil/auto-assign-issue/v1/src/utils.js:33:32)
    at async runAction (/home/runner/work/_actions/pozil/auto-assign-issue/v1/src/action.js:95:29)
Caused by: HttpError: Not Found
    at /home/runner/work/_actions/pozil/auto-assign-issue/v1/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async getTeamMembers (/home/runner/work/_actions/pozil/auto-assign-issue/v1/src/utils.js:33:32)
    at async runAction (/home/runner/work/_actions/pozil/auto-assign-issue/v1/src/action.js:95:29)
```

(I may also be specifying the team incorrectly. Is it `teams: @<org>/<team-name>`, `teams: <org>/<team-name>`, or just `teams: <team-name>`?)

**Comment by figadore** [comment]
ignore me, it just started working, not sure why
and to answer my sub-question, the correct format is `teams: <team-name>` as the readme seems to indicate

**Comment by pozil** [comment]
Glad that you were able to solve the issue.
There's a team example in the readme but I'll update the docs to make the format even clearer.
